-- MySQL Script generated by MySQL Workbench
-- Mon Aug  3 21:51:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Invoices
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Invoices` ;

-- -----------------------------------------------------
-- Schema Invoices
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Invoices` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Invoices` ;

-- -----------------------------------------------------
-- Table `Invoices`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `ciudad` VARCHAR(45) NULL,
  `cod_postal` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `contacto_1` VARCHAR(45) NULL,
  `contacto_2` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Emisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Emisor` (
  `idEmisor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `comuna` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `logo` BLOB NULL,
  `logo_footer` BLOB NULL,
  PRIMARY KEY (`idEmisor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `total` INT NULL,
  `idEmisor` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idInvoice`),
  CONSTRAINT `fk_Invoice_Emisor2`
    FOREIGN KEY (`idEmisor`)
    REFERENCES `Invoices`.`Emisor` (`idEmisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Estado2`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Invoices`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Invoices`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `run` VARCHAR(10) NULL,
  `direccion` VARCHAR(100) NULL,
  `cuenta` VARCHAR(100) NULL,
  `direccion_banco` VARCHAR(45) NULL,
  `swift` VARCHAR(45) NULL,
  `idEmisor` INT NOT NULL,
  PRIMARY KEY (`idBanco`),
  CONSTRAINT `fk_Banco_Emisor1`
    FOREIGN KEY (`idEmisor`)
    REFERENCES `Invoices`.`Emisor` (`idEmisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoices`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invoices`.`Detalle` (
  `idInvoice` INT NOT NULL,
  `idItem` INT NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `valor` INT NULL,
  PRIMARY KEY (`idItem`, `idInvoice`),
  CONSTRAINT `fk_Invoice_has_Item_Invoice1`
    FOREIGN KEY (`idInvoice`)
    REFERENCES `Invoices`.`Invoice` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_has_Item_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `Invoices`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Invoices`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `Invoices`;
INSERT INTO `Invoices`.`Cliente` (`idCliente`, `nombre`, `direccion`, `ciudad`, `cod_postal`, `pais`, `telefono`, `contacto_1`, `contacto_2`) VALUES (1, 'MSI Computer Corp.', '901 Canada Court', 'City of Industry', 'CA 91748', 'United States', '+1-626-9130818', 'Samuel Rojas', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Invoices`.`Emisor`
-- -----------------------------------------------------
START TRANSACTION;
USE `Invoices`;
INSERT INTO `Invoices`.`Emisor` (`idEmisor`, `nombre`, `direccion`, `number`, `comuna`, `ciudad`, `pais`, `telefono`, `url`, `logo`, `logo_footer`) VALUES (1, 'OZEROS', 'Los Boldos', '12492', 'El Bosque', 'Santiago', 'Chile', '+56-9-75175766', 'www.ozeros.com', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Invoices`.`Estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `Invoices`;
INSERT INTO `Invoices`.`Estado` (`idEstado`, `descripcion`) VALUES (1, 'Pendiente');
INSERT INTO `Invoices`.`Estado` (`idEstado`, `descripcion`) VALUES (2, 'Pagado');
INSERT INTO `Invoices`.`Estado` (`idEstado`, `descripcion`) VALUES (3, 'Anulado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Invoices`.`Banco`
-- -----------------------------------------------------
START TRANSACTION;
USE `Invoices`;
INSERT INTO `Invoices`.`Banco` (`idBanco`, `banco`, `nombre`, `run`, `direccion`, `cuenta`, `direccion_banco`, `swift`, `idEmisor`) VALUES (1, 'Santander-Chile', 'Jeremy Roberto Perez Diaz', '15543042-7', 'Los Boldos #12492', '0-000-75-79955-1', 'Bandera 140, Santiago Chile', 'BSCHCLRM', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Invoices`.`Item`
-- -----------------------------------------------------
START TRANSACTION;
USE `Invoices`;
INSERT INTO `Invoices`.`Item` (`idItem`, `descripcion`) VALUES (1, 'Review');
INSERT INTO `Invoices`.`Item` (`idItem`, `descripcion`) VALUES (2, 'Web-Banner');
INSERT INTO `Invoices`.`Item` (`idItem`, `descripcion`) VALUES (3, 'Publishing');
INSERT INTO `Invoices`.`Item` (`idItem`, `descripcion`) VALUES (4, 'Overclocking');
INSERT INTO `Invoices`.`Item` (`idItem`, `descripcion`) VALUES (5, 'Advisory');

COMMIT;

